sudo: false
language: ruby
cache: bundler
rvm:
- 2.5
- 2.6
- ruby-head
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
before_install:
- gem update --system
- gem install bundler
install:
- bundle install --jobs=3 --retry=3
script:
- bundle exec rspec
- bundle exec rubocop
- bundle exec fasterer
notifications:
  email: false
  slack:
    secure: Hcdz1aigAkFPa37QSLo73MxwpUbUL5nE3aCVT6AhTTMijFg4Cl8u4qiZyER1sSXQzT2CTnG8ybZbSe7ehXmWtfgEqsFZCRc8qz6XkCQENayatGpQj+sokwEoGn2HWyPs5xXBxqW3RHx95Pf1qCJehOvS2Xwz0PwxsxUz5ZhRyR2lMbImcCsocDJXnOwDFvni6sOu5C+5S+WsZQMRs/XHlAeg1SE++ej8BuwQU3fTGO306ZR/jfszB0hBzlNrgUwRBejEd5P12AdE/VZ8ZjLP7xEH/Pj/dZsYx39sncmedQ6C+MG76ziT0SrZL7sfK+r6n9yCx/9StgpYpkQ6VWQ2iCxfaKj9U4VoCcA8ysPGZx4k4l6Ri7/h1isGFXhUrGYjA1HBIfaIdUtrXHSjKrqaCNwU2HIoWFPud8njFwQy8I2NeqqUw0GWO33la0QwNtTlO4z30vMCJijSa0nFFVkU6aWDUfPscrzFOakyzD41aEkykdv0Lky9HQjbSmf5D6KjvzNTQr8Erxv+dyzbcPYH86dSN2OrVbB3TgvvN2xjFaqySbpMMRuw6DWq/xtgOuQ27gRziGUULt183VeoRFre2yFUBCLIYVXsL26NF5Ml5nxDWodJ1Wq+foiYZmbVHsq/k+H+W6PcHDUG5v368YqEk6QqaG1LUNcNkUKwABF4n+c=
